export const specialOffersArray = [
  {
    school: [
      {
        id: 0,
        isInDemand: false,
        courseCode: 10988,
        courseName: "voluptate",
        SPS: "$2,803.96",
        SPSNTUTES: "$2,094.18",
        SPSEnrolURL: "incididunt.com",
        SPSNTUTESURL: "dolor.com",
      },
      {
        id: 1,
        isInDemand: false,
        courseCode: 10999,
        courseName: "dolore",
        SPS: "$2,676.53",
        SPSNTUTES: "$2,317.43",
        SPSEnrolURL: "et.com",
        SPSNTUTESURL: "voluptate.com",
      },
      {
        id: 2,
        isInDemand: true,
        courseCode: 10965,
        courseName: "velit",
        SPS: "$3,674.08",
        SPSNTUTES: "$2,548.90",
        SPSEnrolURL: "laborum.com",
        SPSNTUTESURL: "sunt.com",
      },
      {
        id: 3,
        isInDemand: true,
        courseCode: 10378,
        courseName: "do",
        SPS: "$2,114.85",
        SPSNTUTES: "$2,441.61",
        SPSEnrolURL: "commodo.com",
        SPSNTUTESURL: "esse.com",
      },
      {
        id: 4,
        isInDemand: true,
        courseCode: 10769,
        courseName: "ad",
        SPS: "$2,355.84",
        SPSNTUTES: "$1,112.49",
        SPSEnrolURL: "elit.com",
        SPSNTUTESURL: "aliqua.com",
      },
      {
        id: 5,
        isInDemand: true,
        courseCode: 10058,
        courseName: "cillum",
        SPS: "$2,021.83",
        SPSNTUTES: "$3,128.18",
        SPSEnrolURL: "aliqua.com",
        SPSNTUTESURL: "Lorem.com",
      },
      {
        id: 6,
        isInDemand: false,
        courseCode: 10484,
        courseName: "ex",
        SPS: "$2,802.69",
        SPSNTUTES: "$3,811.50",
        SPSEnrolURL: "cillum.com",
        SPSNTUTESURL: "ipsum.com",
      },
      {
        id: 7,
        isInDemand: false,
        courseCode: 10560,
        courseName: "culpa",
        SPS: "$1,617.40",
        SPSNTUTES: "$1,469.26",
        SPSEnrolURL: "est.com",
        SPSNTUTESURL: "ullamco.com",
      },
      {
        id: 8,
        isInDemand: false,
        courseCode: 10487,
        courseName: "officia",
        SPS: "$3,644.37",
        SPSNTUTES: "$2,591.26",
        SPSEnrolURL: "nostrud.com",
        SPSNTUTESURL: "deserunt.com",
      },
      {
        id: 9,
        isInDemand: true,
        courseCode: 10507,
        courseName: "veniam",
        SPS: "$1,183.59",
        SPSNTUTES: "$2,419.94",
        SPSEnrolURL: "nisi.com",
        SPSNTUTESURL: "anim.com",
      },
      {
        id: 10,
        isInDemand: true,
        courseCode: 10684,
        courseName: "exercitation",
        SPS: "$2,873.20",
        SPSNTUTES: "$1,485.24",
        SPSEnrolURL: "ipsum.com",
        SPSNTUTESURL: "sunt.com",
      },
      {
        id: 11,
        isInDemand: false,
        courseCode: 10577,
        courseName: "id",
        SPS: "$1,731.14",
        SPSNTUTES: "$2,598.49",
        SPSEnrolURL: "incididunt.com",
        SPSNTUTESURL: "quis.com",
      },
      {
        id: 12,
        isInDemand: true,
        courseCode: 10947,
        courseName: "elit",
        SPS: "$2,249.02",
        SPSNTUTES: "$3,944.28",
        SPSEnrolURL: "dolor.com",
        SPSNTUTESURL: "esse.com",
      },
      {
        id: 13,
        isInDemand: true,
        courseCode: 10220,
        courseName: "proident",
        SPS: "$1,716.30",
        SPSNTUTES: "$3,785.83",
        SPSEnrolURL: "cillum.com",
        SPSNTUTESURL: "aliquip.com",
      },
      {
        id: 14,
        isInDemand: true,
        courseCode: 10734,
        courseName: "proident",
        SPS: "$2,080.41",
        SPSNTUTES: "$1,915.20",
        SPSEnrolURL: "elit.com",
        SPSNTUTESURL: "irure.com",
      },
      {
        id: 15,
        isInDemand: false,
        courseCode: 10882,
        courseName: "sit",
        SPS: "$2,216.71",
        SPSNTUTES: "$3,360.10",
        SPSEnrolURL: "ut.com",
        SPSNTUTESURL: "nisi.com",
      },
      {
        id: 16,
        isInDemand: false,
        courseCode: 10049,
        courseName: "commodo",
        SPS: "$1,995.46",
        SPSNTUTES: "$1,286.41",
        SPSEnrolURL: "duis.com",
        SPSNTUTESURL: "ad.com",
      },
      {
        id: 17,
        isInDemand: true,
        courseCode: 10572,
        courseName: "duis",
        SPS: "$2,598.37",
        SPSNTUTES: "$3,283.82",
        SPSEnrolURL: "eu.com",
        SPSNTUTESURL: "amet.com",
      },
      {
        id: 18,
        isInDemand: false,
        courseCode: 10328,
        courseName: "nulla",
        SPS: "$3,424.21",
        SPSNTUTES: "$2,147.16",
        SPSEnrolURL: "voluptate.com",
        SPSNTUTESURL: "ex.com",
      },
      {
        id: 19,
        isInDemand: true,
        courseCode: 10754,
        courseName: "sunt",
        SPS: "$3,867.17",
        SPSNTUTES: "$1,903.25",
        SPSEnrolURL: "velit.com",
        SPSNTUTESURL: "aute.com",
      },
    ],
  },
  {
    school: [
      {
        id: 0,
        isInDemand: false,
        courseCode: 10844,
        courseName: "sit",
        SPS: "$3,251.01",
        SPSNTUTES: "$1,486.78",
        SPSEnrolURL: "sit.com",
        SPSNTUTESURL: "voluptate.com",
      },
      {
        id: 1,
        isInDemand: true,
        courseCode: 10375,
        courseName: "esse",
        SPS: "$3,965.78",
        SPSNTUTES: "$1,700.61",
        SPSEnrolURL: "enim.com",
        SPSNTUTESURL: "est.com",
      },
      {
        id: 2,
        isInDemand: true,
        courseCode: 10915,
        courseName: "commodo",
        SPS: "$2,206.79",
        SPSNTUTES: "$2,581.98",
        SPSEnrolURL: "culpa.com",
        SPSNTUTESURL: "eiusmod.com",
      },
      {
        id: 3,
        isInDemand: false,
        courseCode: 10880,
        courseName: "reprehenderit",
        SPS: "$1,470.62",
        SPSNTUTES: "$2,913.03",
        SPSEnrolURL: "anim.com",
        SPSNTUTESURL: "aute.com",
      },
      {
        id: 4,
        isInDemand: false,
        courseCode: 10896,
        courseName: "esse",
        SPS: "$2,193.87",
        SPSNTUTES: "$1,235.91",
        SPSEnrolURL: "culpa.com",
        SPSNTUTESURL: "consectetur.com",
      },
      {
        id: 5,
        isInDemand: false,
        courseCode: 10157,
        courseName: "eu",
        SPS: "$3,188.57",
        SPSNTUTES: "$2,532.32",
        SPSEnrolURL: "enim.com",
        SPSNTUTESURL: "laborum.com",
      },
      {
        id: 6,
        isInDemand: true,
        courseCode: 10359,
        courseName: "ipsum",
        SPS: "$1,266.11",
        SPSNTUTES: "$2,753.31",
        SPSEnrolURL: "fugiat.com",
        SPSNTUTESURL: "velit.com",
      },
      {
        id: 7,
        isInDemand: true,
        courseCode: 10655,
        courseName: "enim",
        SPS: "$3,264.51",
        SPSNTUTES: "$2,917.28",
        SPSEnrolURL: "cupidatat.com",
        SPSNTUTESURL: "do.com",
      },
      {
        id: 8,
        isInDemand: false,
        courseCode: 10362,
        courseName: "laboris",
        SPS: "$3,723.09",
        SPSNTUTES: "$2,478.96",
        SPSEnrolURL: "consectetur.com",
        SPSNTUTESURL: "cillum.com",
      },
      {
        id: 9,
        isInDemand: true,
        courseCode: 10932,
        courseName: "tempor",
        SPS: "$3,705.57",
        SPSNTUTES: "$3,345.73",
        SPSEnrolURL: "id.com",
        SPSNTUTESURL: "deserunt.com",
      },
      {
        id: 10,
        isInDemand: false,
        courseCode: 10616,
        courseName: "enim",
        SPS: "$1,475.43",
        SPSNTUTES: "$3,235.03",
        SPSEnrolURL: "sint.com",
        SPSNTUTESURL: "tempor.com",
      },
      {
        id: 11,
        isInDemand: false,
        courseCode: 10089,
        courseName: "deserunt",
        SPS: "$1,274.08",
        SPSNTUTES: "$2,493.51",
        SPSEnrolURL: "Lorem.com",
        SPSNTUTESURL: "enim.com",
      },
      {
        id: 12,
        isInDemand: false,
        courseCode: 10910,
        courseName: "excepteur",
        SPS: "$1,808.33",
        SPSNTUTES: "$3,646.37",
        SPSEnrolURL: "velit.com",
        SPSNTUTESURL: "qui.com",
      },
      {
        id: 13,
        isInDemand: false,
        courseCode: 10045,
        courseName: "deserunt",
        SPS: "$2,224.21",
        SPSNTUTES: "$2,837.76",
        SPSEnrolURL: "est.com",
        SPSNTUTESURL: "laborum.com",
      },
      {
        id: 14,
        isInDemand: false,
        courseCode: 10037,
        courseName: "aliquip",
        SPS: "$3,926.01",
        SPSNTUTES: "$2,097.50",
        SPSEnrolURL: "aliqua.com",
        SPSNTUTESURL: "veniam.com",
      },
      {
        id: 15,
        isInDemand: false,
        courseCode: 10463,
        courseName: "exercitation",
        SPS: "$1,862.54",
        SPSNTUTES: "$2,583.12",
        SPSEnrolURL: "laborum.com",
        SPSNTUTESURL: "eu.com",
      },
      {
        id: 16,
        isInDemand: true,
        courseCode: 10042,
        courseName: "id",
        SPS: "$3,195.93",
        SPSNTUTES: "$3,444.15",
        SPSEnrolURL: "adipisicing.com",
        SPSNTUTESURL: "irure.com",
      },
      {
        id: 17,
        isInDemand: true,
        courseCode: 10382,
        courseName: "nisi",
        SPS: "$3,350.06",
        SPSNTUTES: "$2,330.59",
        SPSEnrolURL: "nostrud.com",
        SPSNTUTESURL: "nisi.com",
      },
      {
        id: 18,
        isInDemand: true,
        courseCode: 10387,
        courseName: "anim",
        SPS: "$2,060.29",
        SPSNTUTES: "$2,560.36",
        SPSEnrolURL: "et.com",
        SPSNTUTESURL: "voluptate.com",
      },
      {
        id: 19,
        isInDemand: false,
        courseCode: 10405,
        courseName: "esse",
        SPS: "$1,586.71",
        SPSNTUTES: "$3,811.07",
        SPSEnrolURL: "ad.com",
        SPSNTUTESURL: "dolor.com",
      },
    ],
  },
  {
    school: [
      {
        id: 0,
        isInDemand: false,
        courseCode: 10369,
        courseName: "esse",
        SPS: "$3,356.63",
        SPSNTUTES: "$3,477.96",
        SPSEnrolURL: "veniam.com",
        SPSNTUTESURL: "anim.com",
      },
      {
        id: 1,
        isInDemand: false,
        courseCode: 10131,
        courseName: "ut",
        SPS: "$3,184.08",
        SPSNTUTES: "$2,361.00",
        SPSEnrolURL: "laborum.com",
        SPSNTUTESURL: "culpa.com",
      },
      {
        id: 2,
        isInDemand: false,
        courseCode: 10986,
        courseName: "ut",
        SPS: "$3,015.83",
        SPSNTUTES: "$2,173.25",
        SPSEnrolURL: "consectetur.com",
        SPSNTUTESURL: "cillum.com",
      },
      {
        id: 3,
        isInDemand: false,
        courseCode: 10277,
        courseName: "reprehenderit",
        SPS: "$1,059.42",
        SPSNTUTES: "$1,915.53",
        SPSEnrolURL: "sit.com",
        SPSNTUTESURL: "id.com",
      },
      {
        id: 4,
        isInDemand: false,
        courseCode: 10646,
        courseName: "irure",
        SPS: "$2,142.81",
        SPSNTUTES: "$3,977.13",
        SPSEnrolURL: "mollit.com",
        SPSNTUTESURL: "aute.com",
      },
      {
        id: 5,
        isInDemand: true,
        courseCode: 10554,
        courseName: "mollit",
        SPS: "$2,899.56",
        SPSNTUTES: "$3,050.11",
        SPSEnrolURL: "excepteur.com",
        SPSNTUTESURL: "ullamco.com",
      },
      {
        id: 6,
        isInDemand: true,
        courseCode: 10327,
        courseName: "non",
        SPS: "$3,003.27",
        SPSNTUTES: "$1,407.24",
        SPSEnrolURL: "do.com",
        SPSNTUTESURL: "laboris.com",
      },
      {
        id: 7,
        isInDemand: false,
        courseCode: 10187,
        courseName: "veniam",
        SPS: "$2,596.81",
        SPSNTUTES: "$3,126.32",
        SPSEnrolURL: "culpa.com",
        SPSNTUTESURL: "eu.com",
      },
      {
        id: 8,
        isInDemand: true,
        courseCode: 10220,
        courseName: "sit",
        SPS: "$2,948.43",
        SPSNTUTES: "$3,900.21",
        SPSEnrolURL: "velit.com",
        SPSNTUTESURL: "exercitation.com",
      },
      {
        id: 9,
        isInDemand: true,
        courseCode: 10835,
        courseName: "mollit",
        SPS: "$2,439.96",
        SPSNTUTES: "$2,191.46",
        SPSEnrolURL: "tempor.com",
        SPSNTUTESURL: "in.com",
      },
      {
        id: 10,
        isInDemand: false,
        courseCode: 10619,
        courseName: "tempor",
        SPS: "$1,820.77",
        SPSNTUTES: "$1,259.87",
        SPSEnrolURL: "anim.com",
        SPSNTUTESURL: "sint.com",
      },
      {
        id: 11,
        isInDemand: true,
        courseCode: 10591,
        courseName: "voluptate",
        SPS: "$1,980.36",
        SPSNTUTES: "$3,637.71",
        SPSEnrolURL: "laborum.com",
        SPSNTUTESURL: "labore.com",
      },
      {
        id: 12,
        isInDemand: true,
        courseCode: 10995,
        courseName: "minim",
        SPS: "$2,778.23",
        SPSNTUTES: "$3,318.73",
        SPSEnrolURL: "dolor.com",
        SPSNTUTESURL: "culpa.com",
      },
      {
        id: 13,
        isInDemand: true,
        courseCode: 10167,
        courseName: "ex",
        SPS: "$1,760.27",
        SPSNTUTES: "$1,905.14",
        SPSEnrolURL: "ut.com",
        SPSNTUTESURL: "sint.com",
      },
      {
        id: 14,
        isInDemand: true,
        courseCode: 10288,
        courseName: "consequat",
        SPS: "$2,244.98",
        SPSNTUTES: "$3,132.14",
        SPSEnrolURL: "culpa.com",
        SPSNTUTESURL: "qui.com",
      },
      {
        id: 15,
        isInDemand: true,
        courseCode: 10609,
        courseName: "voluptate",
        SPS: "$1,098.76",
        SPSNTUTES: "$3,234.22",
        SPSEnrolURL: "aute.com",
        SPSNTUTESURL: "nostrud.com",
      },
      {
        id: 16,
        isInDemand: false,
        courseCode: 10383,
        courseName: "officia",
        SPS: "$2,126.02",
        SPSNTUTES: "$3,151.83",
        SPSEnrolURL: "mollit.com",
        SPSNTUTESURL: "mollit.com",
      },
      {
        id: 17,
        isInDemand: true,
        courseCode: 10815,
        courseName: "non",
        SPS: "$1,887.69",
        SPSNTUTES: "$3,662.58",
        SPSEnrolURL: "velit.com",
        SPSNTUTESURL: "irure.com",
      },
      {
        id: 18,
        isInDemand: true,
        courseCode: 10705,
        courseName: "elit",
        SPS: "$2,602.08",
        SPSNTUTES: "$1,500.39",
        SPSEnrolURL: "exercitation.com",
        SPSNTUTESURL: "irure.com",
      },
      {
        id: 19,
        isInDemand: true,
        courseCode: 10394,
        courseName: "nostrud",
        SPS: "$3,192.36",
        SPSNTUTES: "$2,958.10",
        SPSEnrolURL: "commodo.com",
        SPSNTUTESURL: "ex.com",
      },
    ],
  },
  {
    school: [
      {
        id: 0,
        isInDemand: true,
        courseCode: 10594,
        courseName: "irure",
        SPS: "$1,554.39",
        SPSNTUTES: "$2,797.70",
        SPSEnrolURL: "amet.com",
        SPSNTUTESURL: "ullamco.com",
      },
      {
        id: 1,
        isInDemand: true,
        courseCode: 10218,
        courseName: "nisi",
        SPS: "$3,491.77",
        SPSNTUTES: "$1,242.80",
        SPSEnrolURL: "reprehenderit.com",
        SPSNTUTESURL: "est.com",
      },
      {
        id: 2,
        isInDemand: true,
        courseCode: 10788,
        courseName: "laborum",
        SPS: "$3,614.40",
        SPSNTUTES: "$3,465.25",
        SPSEnrolURL: "reprehenderit.com",
        SPSNTUTESURL: "id.com",
      },
      {
        id: 3,
        isInDemand: true,
        courseCode: 10974,
        courseName: "ad",
        SPS: "$1,856.96",
        SPSNTUTES: "$2,274.73",
        SPSEnrolURL: "nisi.com",
        SPSNTUTESURL: "officia.com",
      },
      {
        id: 4,
        isInDemand: false,
        courseCode: 10267,
        courseName: "reprehenderit",
        SPS: "$2,955.62",
        SPSNTUTES: "$3,714.60",
        SPSEnrolURL: "ut.com",
        SPSNTUTESURL: "veniam.com",
      },
      {
        id: 5,
        isInDemand: true,
        courseCode: 10589,
        courseName: "duis",
        SPS: "$3,282.61",
        SPSNTUTES: "$3,873.50",
        SPSEnrolURL: "et.com",
        SPSNTUTESURL: "ipsum.com",
      },
      {
        id: 6,
        isInDemand: false,
        courseCode: 10388,
        courseName: "ex",
        SPS: "$3,361.23",
        SPSNTUTES: "$3,795.77",
        SPSEnrolURL: "officia.com",
        SPSNTUTESURL: "culpa.com",
      },
      {
        id: 7,
        isInDemand: true,
        courseCode: 10323,
        courseName: "laborum",
        SPS: "$2,912.80",
        SPSNTUTES: "$2,520.05",
        SPSEnrolURL: "culpa.com",
        SPSNTUTESURL: "minim.com",
      },
      {
        id: 8,
        isInDemand: false,
        courseCode: 10190,
        courseName: "nostrud",
        SPS: "$1,324.35",
        SPSNTUTES: "$2,224.87",
        SPSEnrolURL: "elit.com",
        SPSNTUTESURL: "tempor.com",
      },
      {
        id: 9,
        isInDemand: false,
        courseCode: 10714,
        courseName: "do",
        SPS: "$1,818.63",
        SPSNTUTES: "$1,671.65",
        SPSEnrolURL: "nulla.com",
        SPSNTUTESURL: "voluptate.com",
      },
      {
        id: 10,
        isInDemand: false,
        courseCode: 10644,
        courseName: "ex",
        SPS: "$1,817.64",
        SPSNTUTES: "$1,147.00",
        SPSEnrolURL: "excepteur.com",
        SPSNTUTESURL: "culpa.com",
      },
      {
        id: 11,
        isInDemand: true,
        courseCode: 10940,
        courseName: "dolore",
        SPS: "$2,401.28",
        SPSNTUTES: "$1,929.75",
        SPSEnrolURL: "ad.com",
        SPSNTUTESURL: "qui.com",
      },
      {
        id: 12,
        isInDemand: false,
        courseCode: 10919,
        courseName: "nulla",
        SPS: "$2,360.87",
        SPSNTUTES: "$3,310.53",
        SPSEnrolURL: "et.com",
        SPSNTUTESURL: "fugiat.com",
      },
      {
        id: 13,
        isInDemand: true,
        courseCode: 10110,
        courseName: "dolore",
        SPS: "$1,622.61",
        SPSNTUTES: "$1,699.75",
        SPSEnrolURL: "velit.com",
        SPSNTUTESURL: "aliquip.com",
      },
      {
        id: 14,
        isInDemand: false,
        courseCode: 10637,
        courseName: "do",
        SPS: "$2,448.41",
        SPSNTUTES: "$1,884.71",
        SPSEnrolURL: "fugiat.com",
        SPSNTUTESURL: "et.com",
      },
      {
        id: 15,
        isInDemand: true,
        courseCode: 10048,
        courseName: "consequat",
        SPS: "$3,850.10",
        SPSNTUTES: "$1,853.05",
        SPSEnrolURL: "cillum.com",
        SPSNTUTESURL: "culpa.com",
      },
      {
        id: 16,
        isInDemand: true,
        courseCode: 10265,
        courseName: "ex",
        SPS: "$2,141.25",
        SPSNTUTES: "$1,825.08",
        SPSEnrolURL: "aliqua.com",
        SPSNTUTESURL: "id.com",
      },
      {
        id: 17,
        isInDemand: false,
        courseCode: 10666,
        courseName: "occaecat",
        SPS: "$3,413.40",
        SPSNTUTES: "$1,603.80",
        SPSEnrolURL: "laboris.com",
        SPSNTUTESURL: "do.com",
      },
      {
        id: 18,
        isInDemand: true,
        courseCode: 10495,
        courseName: "culpa",
        SPS: "$3,423.60",
        SPSNTUTES: "$2,348.50",
        SPSEnrolURL: "duis.com",
        SPSNTUTESURL: "mollit.com",
      },
      {
        id: 19,
        isInDemand: true,
        courseCode: 10703,
        courseName: "pariatur",
        SPS: "$1,938.86",
        SPSNTUTES: "$2,388.24",
        SPSEnrolURL: "dolor.com",
        SPSNTUTESURL: "nulla.com",
      },
    ],
  },
  {
    school: [
      {
        id: 0,
        isInDemand: false,
        courseCode: 10769,
        courseName: "quis",
        SPS: "$1,169.94",
        SPSNTUTES: "$1,676.83",
        SPSEnrolURL: "ipsum.com",
        SPSNTUTESURL: "duis.com",
      },
      {
        id: 1,
        isInDemand: false,
        courseCode: 10448,
        courseName: "voluptate",
        SPS: "$2,200.80",
        SPSNTUTES: "$1,188.65",
        SPSEnrolURL: "excepteur.com",
        SPSNTUTESURL: "aute.com",
      },
      {
        id: 2,
        isInDemand: true,
        courseCode: 10875,
        courseName: "irure",
        SPS: "$3,545.34",
        SPSNTUTES: "$3,480.75",
        SPSEnrolURL: "nulla.com",
        SPSNTUTESURL: "velit.com",
      },
      {
        id: 3,
        isInDemand: false,
        courseCode: 10636,
        courseName: "deserunt",
        SPS: "$2,018.09",
        SPSNTUTES: "$1,328.58",
        SPSEnrolURL: "ex.com",
        SPSNTUTESURL: "consectetur.com",
      },
      {
        id: 4,
        isInDemand: false,
        courseCode: 10672,
        courseName: "nisi",
        SPS: "$2,820.38",
        SPSNTUTES: "$2,805.00",
        SPSEnrolURL: "proident.com",
        SPSNTUTESURL: "esse.com",
      },
      {
        id: 5,
        isInDemand: false,
        courseCode: 10229,
        courseName: "elit",
        SPS: "$2,623.22",
        SPSNTUTES: "$1,241.47",
        SPSEnrolURL: "mollit.com",
        SPSNTUTESURL: "nulla.com",
      },
      {
        id: 6,
        isInDemand: true,
        courseCode: 10350,
        courseName: "consequat",
        SPS: "$2,909.03",
        SPSNTUTES: "$2,920.56",
        SPSEnrolURL: "eu.com",
        SPSNTUTESURL: "labore.com",
      },
      {
        id: 7,
        isInDemand: false,
        courseCode: 10364,
        courseName: "laborum",
        SPS: "$1,900.36",
        SPSNTUTES: "$2,921.93",
        SPSEnrolURL: "nisi.com",
        SPSNTUTESURL: "do.com",
      },
      {
        id: 8,
        isInDemand: false,
        courseCode: 10843,
        courseName: "est",
        SPS: "$2,551.20",
        SPSNTUTES: "$1,376.08",
        SPSEnrolURL: "occaecat.com",
        SPSNTUTESURL: "nostrud.com",
      },
      {
        id: 9,
        isInDemand: true,
        courseCode: 10223,
        courseName: "aliqua",
        SPS: "$2,206.25",
        SPSNTUTES: "$1,506.25",
        SPSEnrolURL: "dolore.com",
        SPSNTUTESURL: "occaecat.com",
      },
      {
        id: 10,
        isInDemand: false,
        courseCode: 10916,
        courseName: "commodo",
        SPS: "$3,925.50",
        SPSNTUTES: "$2,950.44",
        SPSEnrolURL: "est.com",
        SPSNTUTESURL: "mollit.com",
      },
      {
        id: 11,
        isInDemand: true,
        courseCode: 10928,
        courseName: "in",
        SPS: "$2,422.14",
        SPSNTUTES: "$3,438.08",
        SPSEnrolURL: "ad.com",
        SPSNTUTESURL: "in.com",
      },
      {
        id: 12,
        isInDemand: false,
        courseCode: 10051,
        courseName: "labore",
        SPS: "$3,478.05",
        SPSNTUTES: "$1,683.01",
        SPSEnrolURL: "officia.com",
        SPSNTUTESURL: "consequat.com",
      },
      {
        id: 13,
        isInDemand: true,
        courseCode: 10861,
        courseName: "in",
        SPS: "$3,653.12",
        SPSNTUTES: "$1,678.47",
        SPSEnrolURL: "sunt.com",
        SPSNTUTESURL: "do.com",
      },
      {
        id: 14,
        isInDemand: true,
        courseCode: 10209,
        courseName: "Lorem",
        SPS: "$2,494.33",
        SPSNTUTES: "$2,725.00",
        SPSEnrolURL: "ex.com",
        SPSNTUTESURL: "nostrud.com",
      },
      {
        id: 15,
        isInDemand: true,
        courseCode: 10382,
        courseName: "mollit",
        SPS: "$3,557.86",
        SPSNTUTES: "$1,781.64",
        SPSEnrolURL: "incididunt.com",
        SPSNTUTESURL: "quis.com",
      },
      {
        id: 16,
        isInDemand: false,
        courseCode: 10465,
        courseName: "proident",
        SPS: "$3,134.77",
        SPSNTUTES: "$1,705.15",
        SPSEnrolURL: "cupidatat.com",
        SPSNTUTESURL: "tempor.com",
      },
      {
        id: 17,
        isInDemand: false,
        courseCode: 10742,
        courseName: "aute",
        SPS: "$2,862.73",
        SPSNTUTES: "$2,929.92",
        SPSEnrolURL: "sit.com",
        SPSNTUTESURL: "dolor.com",
      },
      {
        id: 18,
        isInDemand: false,
        courseCode: 10433,
        courseName: "deserunt",
        SPS: "$3,095.76",
        SPSNTUTES: "$3,976.42",
        SPSEnrolURL: "magna.com",
        SPSNTUTESURL: "magna.com",
      },
      {
        id: 19,
        isInDemand: true,
        courseCode: 10459,
        courseName: "fugiat",
        SPS: "$2,039.11",
        SPSNTUTES: "$1,046.73",
        SPSEnrolURL: "laborum.com",
        SPSNTUTESURL: "adipisicing.com",
      },
    ],
  },
  {
    school: [
      {
        id: 0,
        isInDemand: false,
        courseCode: 10096,
        courseName: "esse",
        SPS: "$2,911.18",
        SPSNTUTES: "$1,530.22",
        SPSEnrolURL: "quis.com",
        SPSNTUTESURL: "duis.com",
      },
      {
        id: 1,
        isInDemand: false,
        courseCode: 10486,
        courseName: "ea",
        SPS: "$2,311.04",
        SPSNTUTES: "$2,374.50",
        SPSEnrolURL: "quis.com",
        SPSNTUTESURL: "aliqua.com",
      },
      {
        id: 2,
        isInDemand: true,
        courseCode: 10468,
        courseName: "aliqua",
        SPS: "$1,336.65",
        SPSNTUTES: "$1,319.54",
        SPSEnrolURL: "excepteur.com",
        SPSNTUTESURL: "laborum.com",
      },
      {
        id: 3,
        isInDemand: false,
        courseCode: 10941,
        courseName: "irure",
        SPS: "$3,621.28",
        SPSNTUTES: "$2,304.42",
        SPSEnrolURL: "aliqua.com",
        SPSNTUTESURL: "voluptate.com",
      },
      {
        id: 4,
        isInDemand: false,
        courseCode: 10348,
        courseName: "amet",
        SPS: "$2,421.75",
        SPSNTUTES: "$2,144.24",
        SPSEnrolURL: "pariatur.com",
        SPSNTUTESURL: "tempor.com",
      },
      {
        id: 5,
        isInDemand: true,
        courseCode: 10246,
        courseName: "aliquip",
        SPS: "$2,769.81",
        SPSNTUTES: "$3,938.87",
        SPSEnrolURL: "ea.com",
        SPSNTUTESURL: "magna.com",
      },
      {
        id: 6,
        isInDemand: false,
        courseCode: 11000,
        courseName: "dolore",
        SPS: "$2,006.03",
        SPSNTUTES: "$3,650.91",
        SPSEnrolURL: "nulla.com",
        SPSNTUTESURL: "dolore.com",
      },
      {
        id: 7,
        isInDemand: true,
        courseCode: 10480,
        courseName: "exercitation",
        SPS: "$3,172.01",
        SPSNTUTES: "$3,134.58",
        SPSEnrolURL: "in.com",
        SPSNTUTESURL: "duis.com",
      },
      {
        id: 8,
        isInDemand: true,
        courseCode: 10072,
        courseName: "incididunt",
        SPS: "$2,079.60",
        SPSNTUTES: "$1,585.54",
        SPSEnrolURL: "anim.com",
        SPSNTUTESURL: "veniam.com",
      },
      {
        id: 9,
        isInDemand: true,
        courseCode: 10841,
        courseName: "sit",
        SPS: "$1,185.97",
        SPSNTUTES: "$2,955.09",
        SPSEnrolURL: "nisi.com",
        SPSNTUTESURL: "sint.com",
      },
      {
        id: 10,
        isInDemand: true,
        courseCode: 10590,
        courseName: "labore",
        SPS: "$1,452.66",
        SPSNTUTES: "$3,736.35",
        SPSEnrolURL: "irure.com",
        SPSNTUTESURL: "nostrud.com",
      },
      {
        id: 11,
        isInDemand: false,
        courseCode: 10667,
        courseName: "aliquip",
        SPS: "$1,233.71",
        SPSNTUTES: "$2,568.83",
        SPSEnrolURL: "voluptate.com",
        SPSNTUTESURL: "amet.com",
      },
      {
        id: 12,
        isInDemand: true,
        courseCode: 10330,
        courseName: "do",
        SPS: "$1,699.61",
        SPSNTUTES: "$1,125.09",
        SPSEnrolURL: "voluptate.com",
        SPSNTUTESURL: "id.com",
      },
      {
        id: 13,
        isInDemand: true,
        courseCode: 10603,
        courseName: "nostrud",
        SPS: "$2,690.98",
        SPSNTUTES: "$1,225.29",
        SPSEnrolURL: "et.com",
        SPSNTUTESURL: "qui.com",
      },
      {
        id: 14,
        isInDemand: false,
        courseCode: 10918,
        courseName: "proident",
        SPS: "$2,027.29",
        SPSNTUTES: "$2,939.26",
        SPSEnrolURL: "aliquip.com",
        SPSNTUTESURL: "aliqua.com",
      },
      {
        id: 15,
        isInDemand: true,
        courseCode: 10086,
        courseName: "fugiat",
        SPS: "$3,705.57",
        SPSNTUTES: "$2,885.35",
        SPSEnrolURL: "ut.com",
        SPSNTUTESURL: "quis.com",
      },
      {
        id: 16,
        isInDemand: true,
        courseCode: 10717,
        courseName: "duis",
        SPS: "$2,885.19",
        SPSNTUTES: "$3,036.94",
        SPSEnrolURL: "cillum.com",
        SPSNTUTESURL: "aliqua.com",
      },
      {
        id: 17,
        isInDemand: true,
        courseCode: 10004,
        courseName: "cillum",
        SPS: "$1,721.95",
        SPSNTUTES: "$2,824.60",
        SPSEnrolURL: "nisi.com",
        SPSNTUTESURL: "veniam.com",
      },
      {
        id: 18,
        isInDemand: false,
        courseCode: 10738,
        courseName: "laborum",
        SPS: "$1,713.97",
        SPSNTUTES: "$2,884.01",
        SPSEnrolURL: "sunt.com",
        SPSNTUTESURL: "deserunt.com",
      },
      {
        id: 19,
        isInDemand: true,
        courseCode: 10903,
        courseName: "mollit",
        SPS: "$1,020.79",
        SPSNTUTES: "$3,781.63",
        SPSEnrolURL: "ad.com",
        SPSNTUTESURL: "et.com",
      },
    ],
  },
]
